cluster:
  name: <CLUSTER_NAME>
  rke2_version: v1.35.5+rke2r2
  registration_endpoint: https://<CONTROL_PLANE_VIP>:9345
  api_endpoint: https://<CONTROL_PLANE_VIP>:6443
  cni: canal

nodes:
  control_plane:
    - hostname: <CONTROL_PLANE_01_HOSTNAME>
      address: <CONTROL_PLANE_01_IP>
      bootstrap: true
    - hostname: <CONTROL_PLANE_02_HOSTNAME>
      address: <CONTROL_PLANE_02_IP>
    - hostname: <CONTROL_PLANE_03_HOSTNAME>
      address: <CONTROL_PLANE_03_IP>
  workers:
    - hostname: <WORKER_01_HOSTNAME>
      address: <WORKER_01_IP>
    - hostname: <WORKER_02_HOSTNAME>
      address: <WORKER_02_IP>
